namespace Cutt
{
    public enum eEffectOccurrenceSpot
    {
        Head_Height,
        Eye_middle_02_L,
        Eye_bottom_L,
        Eye_middle_02_R,
        Eye_bottom_R,
        Neck,
        Chest,
        Waist,
        Hand_Attach_L,
        Thumb_03_L,
        Index_03_L,
        Middle_03_L,
        Ring_03_L,
        Pinky_03_L,
        Hand_Attach_R,
        Thumb_03_R,
        Index_03_R,
        Middle_03_R,
        Ring_03_R,
        Pinky_03_R,
        Ankle_L,
        Toe_L,
        Ankle_R,
        Toe_R
    }
}
