// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using UnityEngine;

namespace LibMMD.Unity3D
{
	public class ModelPart
	{
		public enum SubTextureTypeEnum {
			MatSubTexOff,
			MatSubTexSph,
			MatSubTexSpa,
			MatSubTexSub
		};
		public string ToonPath { get; set;}
		public string TexturePath { get; set;}
		public string SubTexturePath { get; set;}
		public int TriangleNum { get; set;}
		public int BaseShift { get; set;}
		public Color DiffuseColor { get; set;}		
		public Color SpecularColor { get; set;}
		public Color AmbientColor { get; set;}
		public float Shininess { get; set;}
		public bool DrawDoubleFace { get; set;}
		public bool DrawGroundShadow { get; set;}
		public bool CastSelfShadow { get; set;}
		public bool DastSelfShadow { get; set;}
		public bool DrawSelfShadow { get; set;}
		public bool DrawEdge { get; set;}
		public Color EdgeColor { get; set;}
		public float EdgeSize { get; set;}
		public SubTextureTypeEnum SubTextureType { get; set;}
	}
}

