name: Build Windows Player and Android APK

on: 
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  buildForPlatform:
    name: build Player
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        buildName:
          - UmaViewer
        projectPath:
          - ./
        unityVersion:
          - 2022.3.56f1
        targetPlatform:
          - Android # Build an Android APK.
          - StandaloneWindows64 # Build a Windows 64-bit standalone
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - uses: game-ci/unity-builder@v4
        env:
            UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
            UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
            UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          buildName: ${{ matrix.buildName }}
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}

      - name: Zip Binary
        if: matrix.targetPlatform == 'StandaloneWindows64'
        run: zip -r UmaViewer_${{ matrix.targetPlatform }}.zip build/${{ matrix.targetPlatform }}/*

      - name: Upload Artifact for Android
        if: matrix.targetPlatform == 'Android'
        uses: actions/upload-artifact@v4
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}/*
      
      - name: Upload Artifact for Windows
        if: matrix.targetPlatform == 'StandaloneWindows64'
        uses: actions/upload-artifact@v4
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: UmaViewer_StandaloneWindows64.zip

  createRelease:
    needs: buildForPlatform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: build/

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: AutoBuild_${{ github.event.head_commit.id }}
          release_name: UmaViewer_${{ github.event.head_commit.id }}
          draft: false
          prerelease: false

      - name: Upload Windows Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/Build-StandaloneWindows64/UmaViewer_StandaloneWindows64.zip
          asset_name: UmaViewer.zip
          asset_content_type: application/zip

      - name: Upload Android Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/Build-Android/UmaViewer.apk
          asset_name: UmaViewer_Unstable.apk
          asset_content_type: application/vnd.android.package-archive
